### ISSUE TITLE
File Attributes: `interface` not documented

### ISSUE THREAD

**Issue by benmcmorran** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#179]
[The table of allowed values for the `attr` attribute of `file` tags](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_components_pg.html#FileAttributeEnum) only defines `config` and `template`, but [other text in the spec](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/blob/54fbca57780571c19968d29e17798f2bc8dc30fc/doxygen/src/components_schema.txt#L816) alludes to `interface` also being an allowed value. This may overlap with #114

**Comment by jkrech** [comment]
Thanks for pointing this out. The table is correct and the "other text in the spec" describing "select" is an unintended "left over".
The file attribute `interface` was removed some time ago, when we found that there is no real difference between a template and an interface from a tooling perspective. Semantically here the interface was a template that would act as an "interface" (e.g. between two components) rather than being an example application template.
