### ISSUE TITLE
Review CMSIS-Pack generator component concept

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#20]
The currently specified scope of a generator associated with a component is defined here:
[https://arm-software.github.io/CMSIS_5/latest/Pack/html/pdsc_generators_pg.html](https://arm-software.github.io/CMSIS_5/latest/Pack/html/pdsc_generators_pg.html)

![GeneratorComponent.pdf](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/files/8208021/GeneratorComponent_without_animation.pdf)

Initial gap analysis:
- assumption: generators are explicitly triggered to allow explicit user input (add option for non-interactive mode).
- the generator does not have access to project information (e.g. currently selected components or resources).
- the generator does not have access to a list of "generator" files identified by selected components
  - e.g. adding new file element attribute 'attr' = "generator" 
- the generator does not have access to project information of "dependent projects".
- a generator can only be associated with a component but not with a board or device.
- there is no way to express dependencies between generators - only component dependencies are updated and re-evaluated.

**Comment by ReinhardKeil** [comment]
I assume this is for generation of configuration information.  I have a hard time to read the diagrams as they are animated.  Is there a static view to this diagrams.  

Should we consider it during the "Project Manager" work that we started?

**Comment by ReinhardKeil** [comment]
# Proposal for Revised Generator Support

## Workflow assumptions

The composition of a solution of a solution should have the following steps:

- Create `cproject.yml` files and the `csolution.yml` container that refers the projects.
- Select `device:` or `board:` (optionally by using `target-types:`)
- Add `components:` or `layers:` to the `cproject.yml` file
- For components that have configuration, run the generator in configuration mode
   - change pinout, clock, resources, etc.
   - reflect configuration in *.gpdsc file (and related settings files)


## Steps for component selection and configuration

The following explains the generator workflow of CSolution / CBuild for configuration of components:

1. User selects components in `*.cproject.yml` under `components:`
    - When these components require generation, user is notified to run a generator.
    - "CSolution Run GenID” is invoked for a list of components.
    - CSolution generates `*.cgenerator.yml` file that provides project context and a list of user-selected components.
  
2. Running the Generator (for Component Configuration, i.e. pin selection)
     - Generator reads `*.cgenerator.yml` file
     - User performs the configuration is done.
         - Interactive mode (where a settings file is generated)
         - Remote mode (where a settings file is an input) **IS THIS REALLY REQUIRED**
     - Generator creates a `*.gpdsc` file that informs the CSolution tool about
         - (a) the fact that a component is configured and has generated code, 
         - (b) additional components that are the result of some user configuration.

   Discussions: 
     - is a component list or a dependency list
     - Generator might be VS Code plugin or web based

3. User creates CBuild output with CSolution Convert command
      - Both `*.cproject.yml` and `*.gpdsc` are read by Csolution and create the complete list of selected components.
      - If `*.gpdsc` does not contain component information about a component that has `genId` and selected in `*.cproject.yml` the generator configuration is incomplete. This can happen when a component is added at a later step.
      - Likewise the Generator can detect with the `<component User="1">` attribute that a component is longer required. In this case the user is notified to run a generator.

## Enhance Usability

Add Run Generator buttons to Cclass descriptions.

![gen](https://user-images.githubusercontent.com/8268058/156174354-89e2c4e5-c643-4bec-85fb-4b86e7dc15d7.png)


## Workflow

1. For `*.cproject.yml` files that contain selected `<components>` with a `generator` or `genid` attribute the `csolution` manager checks if a file with the name `./<project>/RTE+<target>/genid.cgen.yml` exists.
    - When this file is missing, it is required to use the command `csolution run genid` to start the generator.
    - When this file exists, the `csolution` manager checks if the list of components with `genid` has changed. If this is the case it is required to use the command `csolution run genid` to reconfigure generated components.

2. The command `csolution run genid` creates the file `./<project>/RTE+<target>/genid.cgen.yml` and starts the generator.  The generator creates a *.GDPSC file along with other source files that are required [as specified](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_generators_pg.html#element_generators).

**Example Content of \*.cgen.yml (in this case STM32CubeMX.cgen.yml)**

The `*.cgen.yml` file is passed to generator as argument.

```yml
cgenerator:
  device: STM32F407IGHx
  board: NucleoF407
  solution: C:/tmp/MySolution/MySolution.csolution.yml 
  project: C:/tmp//MySolution/Blinky/Blinky.cproject.yml 
  context: .Debug+Nucelo    # build-type and target-type of the current generated context
  destination: C:/tmp/MySolution/Blinky/RTE+Nucelo/

  packs:                     # packs that are used for the project
    - pack: Keil::STM32F4xx_DFP@2.16.1
      path: C:/CMSIS-PACKS/Keil/STM32F4xx_DFP/2.16.1/
    - pack: Keil::STM32F4xx_BSP@2.1.1
      path: C:/CMSIS-PACKS/Keil/STM32F4xx_BSP/2.1.1/

  components:               # components that have a genid and are specified in *.cproject.yml
    - component: Device:STM32Cube HAL:Common
    - component: Board:LED
```

## Changes to the *.GPDSC file

To indicate that a component was generated due to a user selection in `*.cproject.yml`, the `component` element is extended with `User` attribute.  When set to `1` it indicates that a component is included due to the selection in `*.cproject.yml`.

When a user removes this component in the `*.cproject.yml`, the CSolution could detect that a Run command should be executed.


## Changes to the *.PDSC file

- Add `<key>` to `<generator>` element.  The `key` is used to invoke the generator and pass the `*.cgenerator.yml` file.
  - on Windows to a registry key to invoke the generator tool
  - on Linux and MacOS to an environment variable that specifies how to invoke the generator tool
  - todo: Web based tools?

  
- Add `genId` to `component` element. Indicates that a component is managed by the `<generator>`

- Add `genOwned` to `component` element. Indicates that a component is typically managed by the `<generator>` as it is a secondary component that a user would not select. For example, DMA is a component that is typically required because of a peripheral configuration that requires DMA. Such components may be hidden in an IDE, but should be visible in a project tree.  (??? Do we need this ???)

- Add new file category:
  - `genParms` template parameters
  - `genHeader` header templates for the generator
  - `genSource` source templates for the generator
  - `genHelper` additional files for the generator

**Example:**
```xml
 <generators>
    <!-- This generator is launched if any component referencing this generator by 'id' is selected and the specified <gpdsc> file does not exist -->
    <generator id="STM32CubeMX">
      <description>ST Microelectronics: STCubeMX Environment</description>
      <key>STCubeMX_CGENFILE</key>          <!-- for windows registry key that opens a *.cgenerator.yml file -->
                                            <!-- for Linux / MacOS the key is an environment variable that can start the tool -->
      <web>url</web>                        <!-- for web based tools the url is used and appended by &Cgen=file -->
      <workingDir>$PRTE/Device</workingDir> <!-- path is specified either absolute or relative to gpdsc file -->
      <gpdsc name ="myGen.gpdsc"/>  <!-- PDSC or GPDSC file. If not specified it is the project directory configured by the environment -->
      <files>   <!-- does this make sense? -->
        <file category="genHelper" name="Drivers/STM32F4xx_HAL_Driver/Src/common-file-for-gen.xyz"/>
      </files>
    </generator>
  </generators>

  <taxonomy>
    <description Cclass="Device" generator="STM32CubeMX" doc="Documentation/DM00105879.pdf" >STM32F4xx Hardware Abstraction Layer (HAL) and Drivers</description>
    <description Cclass="Board" generator="STM32CubeMX" doc="Documentation/DM00105879.pdf" >STM32F412 Board Abstraction Layer (HAL) and Drivers</description>
  </taxonomy>


    <component Cclass="Device" Cgroup="STM32Cube HAL" Csub="Common"    Cversion="1.7.9" condition="STM32F4 HAL Common"  genid="STM32CubeMX" >
      <description>Common HAL driver</description>
      <RTE_Components_h>
        #define RTE_DEVICE_HAL_COMMON
      </RTE_Components_h>
      <files>
        <file category="include" name="Drivers/STM32F4xx_HAL_Driver/Inc/"/>
        <file category="header"  name="Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal.h"/>
        <file category="source"  name="Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c"/>
        <file category="genParams" name="Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.json"/>
        <file category="genHeader" name="Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.h.template"/>
        <file category="genSource" name="Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.template"/>
      </files>
    </component>
    <component Cclass="Device" Cgroup="STM32Cube HAL" Csub="ADC"       Cversion="1.7.9" condition="STM32F4 HAL DMA"  genid="STM32CubeMX">
      <description>Analog-to-digital converter (ADC) HAL driver</description>
      <RTE_Components_h>
        #define RTE_DEVICE_HAL_ADC
      </RTE_Components_h>
      <files>
        <file category="source" name="Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c"/>
        <file category="source" name="Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c"/>
        <file category="genParameter" name="Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.json"/>
        <file category="genHeader" name="Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.h.template"/>
        <file category="genSource" name="Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.template"/>
      </files>
    </component>
	  :
    <bundle Cbundle="STM32F4-Discovery" Cclass="Board Support" Cversion="2.0.0">
      <description>STMicroelectronics STM32F4 Discovery Kit</description>
      <doc>http://www.st.com/st-web-ui/static/active/en/resource/technical/document/data_brief/DM00037955.pdf</doc>
      <component Cgroup="LED" Capiversion="1.0.0" condition="STM32F4 HAL GPIO" genid="STM32CubeMX">
        <description>LED Interface for STMicroelectronics STM32F4-Discovery Kit</description>
        <files>
          <file category="source"  name="MDK/Boards/ST/STM32F4-Discovery/Common/LED_F4Discovery.c"/>
          <file category="genParams" name="MDK/Boards/ST/STM32F4-Discovery/Common/LED_F4Discovery.json"/>
          <file category="genHeader" name="MDK/Boards/ST/STM32F4-Discovery/Common/LED_F4Discovery.h.template"/>
          <file category="genSource" name="MDK/Boards/ST/STM32F4-Discovery/Common/LED_F4Discovery.c.template"/>
        </files>
      </component>
```

**Example *.gpdsc file**
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- ******************************************************************************
 * File Name   : FrameworkCubeMX.gpdsc
 * Date        : 23/09/2021 14:18:05
 * Description : Generator PDSC File generated by STM32CubeMX (DO NOT EDIT!)
 ****************************************************************************** -->
<package xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" schemaVersion="1.0" xs:noNamespaceSchemaLocation="PACK.xsd">
  <vendor>Keil</vendor>
  <name>FrameworkCubeMX</name>
  <description>STM32CubeMX generated pack description</description>
  <url>project-path</url>
  <releases>
    <release version="1.0.0">
     - Generated: 23/09/2021 14:18:05
    </release>
  </releases>
  <generators>
    <generator id="STM32CubeMX" Gvendor="STMicroelectronics" Gtool="STM32CubeMX" Gversion="4.10.0">
      <description>STM32CubeMX Environment</description>
      <select Dname="STM32G474RETx" Dvendor="STMicroelectronics:13"/>
      <command>$SMDK\CubeMX\STM32CubeMXLauncher</command>
      <workingDir>$PRTE\Device\STM32G474RETx</workingDir>
      <project_files>
        <file category="include" name="STCubeGenerated/Inc/"/>
        <file category="source" name="STCubeGenerated/Src/main.c" />
        <file category="header" name="STCubeGenerated/Inc/stm32g4xx_it.h"/>
        <file category="source" name="STCubeGenerated/Src/stm32g4xx_it.c"/>
      </project_files>
    </generator>
  </generators>
  <taxonomy>
    <description Cclass="Device" Cgroup="STM32Cube Framework" generator="STM32CubeMX">STM32Cube Framework</description>
  </taxonomy>
  <conditions>
    <condition id="STCubeMX">
      <description>Condition to include CMSIS core, Device Startup and HAL Drivers components</description>
      <require Dvendor="STMicroelectronics:13" Dname="STM32G4*"/>
      <require Cclass="CMSIS"  Cgroup="CORE"/>
      <require Cclass="Device" Cgroup="Startup"/>
      <require Cclass="Device" Cgroup="STM32Cube HAL"/>
    </condition>
  </conditions>
  <components>
    <bundle Cbundle="STM32CubeMX" Cclass="Device" Cversion="1.4.0">
      <component generator="STM32CubeMX" Cvendor="Keil" Cgroup="STM32Cube Framework" Csub="STM32CubeMX" condition="STCubeMX">
        <description>Configuration via STM32CubeMX</description>
        <RTE_Components_h>
          #define RTE_DEVICE_FRAMEWORK_CUBE_MX
        </RTE_Components_h>
        <files>
          <file category="header" name="MX_Device.h"/>
          <file category="header" name="STCubeGenerated/Inc/stm32g4xx_hal_conf.h"/>
          <file category="source" name="STCubeGenerated/Src/stm32g4xx_hal_msp.c"/>
        </files>
      </component>
      <component  Cgroup="Startup" User="1">  <!-- user selected component in *.cproject.yml -->
        <description>System Startup for STMicroelectronics</description>
        <files>
          <file category="source" name="STCubeGenerated/MDK-ARM/startup_stm32g474xx.s" />
          <file category="source" name="STCubeGenerated/Src/system_stm32g4xx.c" />
        </files>
      </component>
    </bundle>
  </components>
</package>
```

**Comment by jkrech** [comment]
We need to agree on using either *.cgenerator.yml or *.cgen.yml above.
In #78 there is three updates that need to be reviewed and reflected above:
a) Revised Additional FileTypes: 
- genParams
- genSettings
- genInput
b) Context specific Generator file format YML vs. JSON (configurable): *.cgenerator.yml 
c) *.cgenerator.yml to provide a list of all files for each selected component including path information

**Comment by ReinhardKeil** [comment]
I believe `genSettings` are not part of the pack itself as this are the settings that are used to configure the parameters.  These settings are project specific (and should be therefore supplied during creation of the project) or this is incorrect.

`genInput` would replace genHeader and genSource as from the perspective of the generator it is not important to know which type of file is created.  Instead, the file extension identifies the filetype (header, source, scatter file, ect.).  Is this correct.

**Comment by ReinhardKeil** [comment]
@fred-r when I understand it correct, the data input format to the handlebars engine JSON. This would be true for:
  - cgenerator - the file that defines the input to the generator
  - fzone data file - the file that contains the resource information of the system

Is it correct that both of these files should have JSON format?

**Comment by ReinhardKeil** [comment]
This is an useful example in this context

CMSIS-Zone example for STM32L5 reworked with Handlebars:
https://github.com/fred-r/CMSIS-Zone/tree/main/Examples/STM32L5

**Comment by fred-r** [comment]
> @fred-r when I understand it correct, the data input format to the handlebars engine JSON. This would be true for:
> 
> * cgenerator - the file that defines the input to the generator
> * fzone data file - the file that contains the resource information of the system
> 
> Is it correct that both of these files should have JSON format?

Yes, in fact the rational behind this proposal is that if a file is not intended to be used by a human-being then JSON is more direct for the tools (serialization) and also the JSO support is built-in in some languages (JS, pyhton).

**Comment by fred-r** [comment]
> I believe `genSettings` are not part of the pack itself as this are the settings that are used to configure the parameters. These settings are project specific (and should be therefore supplied during creation of the project) or this is incorrect.
> 
> `genInput` would replace genHeader and genSource as from the perspective of the generator it is not important to know which type of file is created. Instead, the file extension identifies the filetype (header, source, scatter file, ect.). Is this correct.

Yes,

genSettings is more for the project (and the layer).
genInput is probbaly not a great name but after discussing with my colleagues we concluded that what is important is to identify the inputs for the codegen, not the exact file type (naming rules or extensions can be used for that). This gives the flexibility to support different technologies or to add additional subdivisions without reworking the spec each time.

**Comment by ReinhardKeil** [comment]
Then I would propose the following new file categories for `components`
  - genParms template parameters
  - genInput source templates for the generator and other related input files for the generator

This reduces the number of extensions to what we see is needed today.

**Comment by ReinhardKeil** [comment]
I suggest to complete this discussion under #104

**Comment by fred-r** [comment]
Dear all,

on STM side, we are currently progressing on our flow and usage of the generators.
From a user flow perspective, we are aligned with the proposal.

We confirm that we envision projects with:
- several components invoking the same generator
- 1 component invoking 1 generator

So:

__Components description__
1. The spec must allow us to associate the very same generator to several components.
2. The spec must allow us to provide a global unique identifier per generator: we do not need this to be a direct way to invoke an executable. It can be a unique identifier and then it is up to the project manager (csolution tool) to invoke it properly.

Then:

__Generator Invocation__
The project manager (csolution) must be able to invoke each __unique__ generator: no need to call N times the same generator if several components using it are in the project

__Generator Definition__
Now, regarding the way to define this generator: we can keep the existing arguments for backward compatibility reasons.
But, we also need one more argument to provide the generator input file (cgen.yml/json).

Our current thinking is to introduce a $G argument:
```
    <generator id="myUniqueId">
      <description>An example of Open CMSIS Generator</description>
      <exe>
        <command host="win">generator.bat</command>
        <!-- $S = Device Family Pack base folder -->
        <argument>$S</argument>
        <!-- D = Device (Dname/Dvariant as configured by environment) -->
        <argument>$D</argument>
        <!-- Project path and project name (as configured by environment) -->
        <argument>$P</argument>
        <argument>#P</argument>
        <!-- #name of the gpdsc template contained in this PACK and aligned with GPDSC name-->
        <argument>my_template.gpdsc</argument>
        <!-- #path of the generator input file -->
        <argument>$G</argument>
      </exe>
      <!-- workingDir></workingDir -->
      <!-- path is specified either absolute or relative to PDSC or GPDSC file. If not specified it is the project directory configured by the environment -->
      <gpdsc name="$P\my_gpdsc.gpdsc" />
    </generator>
```

For the format of this input file, we are in favor of "unifying it" with the lock file proposal from @slhultgren.
This file must describe the project "at file level" so that there is no need to go back to the pdsc to understand it.

__Executive Summary__
We need:
1. a spec update to allow multiple components to reference the same generator (more a clarification than a real update)
2. a spec update to introduce the unique generator id concept
3. a spec update to define the generator input file format : hopefully, this can be the same as the lock file format
4. a spec update to introduce the new $G argument in the \<generator\> element
5. a spec update to have new files categories
6. a csolution tool update to invoke only each __unique__ generator and not all generators
7. a csolution tool update to generate the generator input file and pass it with $G

Point to be clarified:
The concept of user selected component passed to the generator is unclear to us.
I guess that if the project composition evolves, then the project manager (csolution) should reinvoke the unique generators "blindly". Then, up to each generator to determine if something needs to be done or not depending on what it does ?
The complexity is more when a file used by a generator gets updated.
If this file is not related to project composition, then the project manager (csolution) has no way to detect this change and determine that a generator must be run again.
Probably here we should not try to deal with it at project manager level.
The "entity" updating the file should be able to invoke the concerned generator, ideally via csolution so that csolution can decide if it runs only the requested generator or all of them.
This might get us to the point identified by Joachim : expressing dependencies between generators.
I am not sure we should shoot for this complexity from day one.
The dependencies could be kept at components level, then I am not sure we should try to have the project manager dealing with all dependencies coming from generators.
Open thoughts : if really we want to go this way, then probably a generator should also define his dependencies (file level) in its definition so that the project manager (csolution) can evaluate it. But I am afraid we will enter a too high complexity level here.
Probably the project manager (csolution) should care only for components.

**Comment by jkrech** [comment]
Continued here #104
