### ISSUE TITLE
How to put conditions to select a file according to hardware specificities ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#217]
In the current spec, the conditions have a limited scope.

My use-case is:
- if my SoC has IP version x then select file_x.c
- if my SoC has IP version y then select file_y.c

I planned to use the feature:
https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_feature

But it is unclear to me how precise I can be here and I cannot use it in conditions.

**Comment by jkrech** [comment]
@mdortel-stm thanks a lot for responding.
@fred-r the [`<feature>`](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main)/html/pdsc_family_pg.html#element_feature) is used for display/search purposes rather than for component/file condition purposes.
see an example here, where this information is displayed: https://www.keil.com/dd2/stmicroelectronics/stm32f407ietx/
or here you can even search devices based on features:
https://developer.arm.com/tools-and-software/embedded/cmsis/cmsis-search
Does that answer your question?

**Comment by fred-r** [comment]
@jkrech : as you confirmed that we will be able to put conditions on the HW description, this is fine for me.
