### ISSUE TITLE
enrich `Dsecure` condition with `FullSecure` test

### ISSUE THREAD

**Issue by tarek-bochkati** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#319]
### Current situation

`Dsecure` accepts 3 possible values `Non-secure`, `Secure` and `TZ-disabled`.

### The problem

We generally use `Non-secure` and `Secure` conditions to provide Startup component files that serves co-existing secure and non-secure applications.

To enrich Startup with files serves only a secure application that uses the full memory space, we need to enrich the `Dsecure` with a value that checks for such condition.

### Proposal

We propose to add `Full-secure` (or equivalent) to permit selecting a set of files to satisfy the use-case where all memory resources are reserved for a single secure application (no jump to non-secure)

**Comment by tarek-bochkati** [comment]
**Update**: In Open-CMSIS-Pack meeting we discussed the potential usage of `TZ-disabled`.

We noted the following:
 * this is semantically incorrect since TZ is "really" enabled
 * memory mapping is different vs TZ-disabled.\
STM32U5 as example:

| `Dsecure`  | `TZ-disabled` | `Secure`     | `Non-secure` |
|------------|---------------|--------------|--------------|
| **FLASH addr** | `0x08000000`  | `0x0C000000` | `0x08000000` |

For the `Full-secure` proposal, we need to use secure mapping (`0x0C000000`) which is different from `TZ-disabled` mapping (`0x08000000`)

**Conclusion**: using `TZ-disabled` do not satisfy this use-case

**Comment by jkrech** [comment]
During the meeting we have also discussed whether there should be a separate attribute indicating that the `Secure` project will not be combined with one or more related `Non-secure` projects. Which means there is no need for resource partitioning and there must not be a cmse-lib.o created.

I think adding another attribute may make things more complicated than necessary.
I prefer the term:

`Secure-only`

**Comment by ReinhardKeil** [comment]
I believe, the issue is wider then just the startup code. We have template projects that help users to get started.
For the STM32U5 these are here:
https://github.com/Open-CMSIS-Pack/STM32U5xx_DFP/blob/main/Keil.STM32U5xx_DFP.pdsc#L1924

Currently the STM32 based projects rely on the features of CubeMX for device configuration.

The reason why I believe this is better covered with template projects is:
  - It is required to setup certain project parameters (i.e. compiler or linker configuration).
  - It may require a specific startup code (currently this is generated by CubeMX)
  - It may require different linker scripts.
  
Maybe it makes sense to create an project example first to see all the aspects. How should we proceed?

**Comment by jkrech** [comment]
In the [`processor:` node of the CMSIS Solution project format](https://www.doulos.com/training/ai-and-deep-learning/deep-learning/practical-deep-learning-online/) the `trustzone:` node can be configured to one of:

`secure | non-secure | off`

an additional setting `secure-only` would not only enable the condition evaluation of `Dsecure="Secure-only"` to true but would also prevent the linker from the attempt to create a `cmse library`.
