### ISSUE TITLE
Unify Syntax of component identifier

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#41]
###  Background: 
We are aiming for a unified/consistent string format for referencing a component either fully or partially qualified.
This does not change the way components are described as part of CMSIS-Pack description.
This string shall be used for component selection (e.g. in the context of project descriptions)  but also for output messages of tools.

### Pattern:
```Cvendor  ::Cclass  [&Cbundle]  :Cgroup  [:Csub]  [&Cvariant]  [@CversionMin [:CversionMax]]```

#### fully specified = uniquely identified
- Cvendor::Cclass:Cgroup@Cversion (without optional Cbundle, Csub, Cvariant):
```ARM::CMSIS:CORE@5.5.0```
- Cvendor::Cclass:Cgroup:Csub:Cvariant@Cversion (without Cbundle):
```ARM::CMSIS:RTOS2:Keil RTX5&Source@5.5.3```
- Cvendor::Cclass@Cbundle:Cgroup:Cvariant@Cversion (without Csub):
```Keil::USB&MDK-Pro:CORE&Release@6.15.1```
- Cvendor::Cclass@Cbundle:Cgroup:Cvariant@Cversion (all):
```Keil::USB&MDK-Pro:Device:HID&Release@6.15.1```

#### partially specified => multiple matches
Rules:
- if an attribute is not specified it is the same as if the attribute equals "*" (e.g. Cvendor="*")
- if an attribute is set to an empty string "~" needs to be used
- the following wildcards are supported '?', '*', [abc]

Examples:
- version range CversionMin:CversionMax (component version >= CversionMin && version < CversionMax)
```ARM::CMSIS.CORE@5.0.0:6.0.0```
- any vendor, any version
```*::Device:Startup&C Startup@*```
equivalent
```Device:Startup&C Startup```
- any bundle that starts with 'MDK' and variant set to empty string
```Keil::USB&MDK*:CORE&~```
- any attribute (except version) exactly matches DSP
```DSP```

**Comment by rwalton-arm** [comment]
> `Cvendor ::Cclass [&Cbundle] :Cgroup [:Csub] [&Cvariant] [@CversionMin [:CversionMax]]`

I don't really understand why some optional attributes (e.g `Cbundle` and `Cvariant`) are prefixed with `&` where other optional attributes are prefixed with `:`. It might be worth explaining this in the "Pattern" section.

> Rules:
> 
>    * if an attribute is not specified it is the same as if the attribute equals `"_"` (e.g. `Cvendor="_"`)

What is the behaviour when an attribute value equals `"_"`?

>    * version range CversionMin:CversionMax (component version >= CversionMin && version < CversionMax)
>       `ARM::CMSIS.CORE@5.0.0:6.0.0`

The version range syntax seems unintuitive. The explanation indicates that this is a half-open range, but that isn't explicit in the syntax. The more commonly used syntax @0xc0170 suggested is explicit about whether the range is inclusive, exclusive or half-open.

**Comment by LMESTM** [comment]
My 2 cents: I agree that >=5.0.0,<6.0.0 seems more understandable than 5.0.0:6.0.0 
The fact than the max version is considered excluded might be a cause of error

**Comment by jkrech** [comment]
Thanks for all the feedback. If I understand correctly we should provide the flexibility to support inclusive and exclusive as well as half open. 
```
(>|>=) minVersion , (<|<=) maxVersion
```
with the option to either specify minVersion or maxVersion or both.
Am I missing something.

**Comment by 0xc0170** [comment]
> a) @0xc0170 where can I find the specification of a version range in Semantic Versioning 2.0? I could not find it.

I could not neither, the only thing in their specification is regex to check the syntax https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string. 
There are couple of implementations providing more details:
- node https://nodesource.com/blog/semver-a-primer/
- crate https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

`^`, `~` are not that well known as we found out (at least our users were often asking about them and there were issues because of these sometimes), most users find intuitive only `=`, `<`, `>` (crate page above shows matching between these and using ranges).

As @rwalton-arm asked about separators in this identifier: what are differences between `::` and `:` : `Keil::USB` vs `MDK-PRO:Device` or `&`. We have 3 different characters, this could lead to lot of mistakes by users. It would help if we add details about these (or reference if it's documented somewhere).  
What challenges we would have if we use one separator `Keil:USB:MDK-Pro:Device:HID:Release` ? would we need a specific separator for optional ones ? If yes, we could end up with just `:` and `&` ?

For version, do we need `@` separator? I assume characters like `<` or `>` and similar would not be allowed as identifier (isn't this like it is in pypi specified, see https://www.python.org/dev/peps/pep-0508/#names what is allowed in python - pypi use regex to check if the package has proper name.
If we follow similar restriction in names, we could add version right after the last identifier:
`Keil::USB&MDK-Pro:Device:HID&Release==6.15.1` would be equal to presented `Keil::USB&MDK-Pro:Device:HID&Release@6.15.1` or if I would specify a range, it would be `Keil::USB&MDK-Pro:Device:HID&Release>=6.15,<7.0`

**Comment by ReinhardKeil** [comment]
`::` separate Cvendor from Cclass.  The Cvendor is optional and frequently derived from context (i.e. device used).  For example `CMSIS-Driver:Ethernet` would resolve to `NXP::CMSIS-Driver:Ethernet` on NXP devices, to 'ST::CMSIS-Driver:Ethernet' on ST devices.

The unique separator `::` allows it to omit Cvendor or specify it as needed.

**Comment by slhultgren** [comment]
If these are written by hand, then it seems hard to know when to separate using `:` or `&` for which optional items and ordering?

More URL-like? Start with optional vendor, then required class and group, then follow with named optional parts.
`(Cvendor::)?Cclass:Cgroup(&(bundle|sub|variant|version|pack|condition)=[ a-zA-Z0-9<=\.\*]+)*`

It could be useful to add pack (vendor + name + version) and condition to this as optional parts as well, otherwise we still won't be able to exactly identify a specific component if desired.

E.g. 
* `CMSIS:Core` => Matches any Cclass==CMSIS && Cgroup==Core
* `ARM::CMSIS:Core` => Matches Cvendor=ARM && Cclass==CMSIS && Cgroup==Core
* `CMSIS:Core&version=5.0.6<=*&sub=SubComp` => Matches Cclass==CMSIS && Cgroup==Core && Csub=SubComp && versions 5.0.6 or higher
* `CMSIS:Core&pack=ARM.CMSIS.5.8.0` => Matches Cclass==CMSIS && Cgroup==Core strictly from the ARM.CMSIS.5.8.0 pack
* `Device:Startup&condition=ARMCM7 CMSIS` => Matches Cclass==Device && Cgroup==Startup && components using the condition "ARMCM7 CMSIS", this can be used to locate specific components that are declaring this condition after the condition has been fulfilled in the project.

While this format is a bit more noisy, it has less implicit interpretations based on order while offering extendability.

**Comment by ReinhardKeil** [comment]
Thanks for all the good suggestions, I suggest we review what has been implemented in 'projmgr' (see here https://github.com/brondani/devtools/blob/mvp-prototype/tools/projmgr/docs/Overview.md#component-names)

After that we should decide if more discussion is required.
